name: Java Maven Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'

    - name: Build with Maven
      run: --batch-mode -DskipTests package

    - name: Run tests
      run: --batch-mode test